### ISSUE TITLE
Problemas con las imágenes

### ISSUE THREAD

**Issue by cmonsalvec** [ControlVehicularSoftware2/GestionDeIncidentes#4]
Favor revisar, pues tengo problemas con las imágenes. Aparentemente es por las rutas de estas.

**Comment by haroldspear** [comment]
Efectivamente, he **reproducido** el problema, en los script no está ubicada la ruta a las imágenes, adjunto capturas de pantalla:
Pimienta:
![image](https://user-images.githubusercontent.com/20802866/51212325-38713a00-18e6-11e9-8ec3-66d514858007.png)

Sal:
![image](https://user-images.githubusercontent.com/20802866/51212342-46bf5600-18e6-11e9-8c70-ea2ee8fd811d.png)

**Comment by haroldspear** [comment]
https://github.com/ControlVehicularSoftware2/GestionDeIncidentes/releases/tag/reduccion_ruidos

**Comment by haroldspear** [comment]
**Clasificación del impacto:** El impacto es muy alto, ya que tiene defectos que son críticos para el funcionamiento de los módulos, se pierde la funcionalidad de todo el sistema.
**Probabilidad de ocurrencia:** La probabilidad de ocurrencia es de un 100%, llevando a un alto impacto.
**Recomendación:** No usar el software hasta que se resuelva el problema. 
**Reportes:** Se le reporta al cliente @cmonsalvec que ya se ha asignado a un miembro del equipo @irenecordova , que resolverá el problema lo más pronto posible, le tendremos al tanto.

**Comment by cmonsalvec** [comment]
Gracias por atender mi pedido. Podrían por favor indicar en su análisis ell tiempo aproximado para solucionar el problema.

**Comment by irenecordova** [comment]
Solución del problema:
![image](https://user-images.githubusercontent.com/20955787/51213850-15e12000-18ea-11e9-9059-b8eb803647a9.png)

**Comment by haroldspear** [comment]
@cmonsalvec El problema ha sido resuelto, en un momento haremos las pruebas del sistema para confirmar en un 100%, por el momento tenemos la noticia que puede continuar usando el software sin problemas conocidos.

**Comment by haroldspear** [comment]
Como no se necesitan entradas las pruebas son de ejecución teniendo estas salidas:

Salida del módulo Pimienta:
![image](https://user-images.githubusercontent.com/20802866/51214116-00202a80-18eb-11e9-8226-61bd79562fed.png)


Salida del módulo Sal:
![image](https://user-images.githubusercontent.com/20802866/51214009-9f90ed80-18ea-11e9-9c81-e6cf037174e8.png)

**Comment by allanalarcon** [comment]
@cmonsalvec Por favor revise el sistema validando la corrección del problema.

**Comment by cmonsalvec** [comment]
Muchas gracias. Por los resultados entregados veo que el sistema aparentemente funciona bien. Sin embargo, no me contestaron antes cuanto tiempo consideraban requerían para solucionar el problema, tampoco veo que me dan acceso al nuevo código para revisar.

**Comment by allanalarcon** [comment]
@cmonsalvec El acceso concedido lo encuentra aquí git clone https://github.com/ControlVehicularSoftware2/GestionDeIncidentes.git

Justo preguntó al momento en que se solucionó el problema por eso no se alcanzó a ver la pregunta.

![image](https://user-images.githubusercontent.com/20955786/51214471-0a8ef400-18ec-11e9-83a6-23392cc3f452.png)

Vamos a proceder a cerrar el issue, luego de un  seguimiento en producción.
